### PR TITLE
User provisioning api to set the user's quota

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by PVince81** [comment]
I haven't reviewed yet and I already have the feeling that this will not work until we fix these:
- https://github.com/owncloud/core/issues/19811
- https://github.com/owncloud/core/issues/19810

**Comment by DeepDiver1975** [comment]
> I haven't reviewed yet and I already have the feeling that this will not work until we fix these:

thanks for these pointer - I'll have a look and try to fix this ....

**Comment by DeepDiver1975** [comment]
> owncloud/core#19810

this one is not affecting us because the values are part of the UserController responses. Provisioning api is not involved.

**Comment by PVince81** [comment]
if no test failed in this PR then we need to add tests for exactly these cases

**Comment by DeepDiver1975** [comment]
> we need to add tests for exactly these cases

tests have been added to master -> merge

**Pull request merged**
