### PR TITLE
Run CI

### PR DESCRIPTION
**Pull request by phil-davis**
to see if it keeps getting JS fails

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 @patrickjahns or ???
The JS tests in drone fail here in the user_management app - even when I just do a "dummy" change like this to trigger CI.

Has something changed "underneath" (in core or some drone or docker image thing or) that would have broken this?

**Comment by phil-davis** [comment]
I noticed because I tried to do a little acceptance test refactoring in #17 and got these same JS test fails.

**Comment by patrickjahns** [comment]
@phil-davis 
Put a commit on top with a fixed `core` plugin to also account for the symlinks - lets see if this works again and if yes - I'll create a PR to the drone plugin and merge it

**Comment by patrickjahns** [comment]
@phil-davis 
drone seems green here - once https://github.com/owncloud-ci/core/pull/10 is merged - all builds relying on a git branch should work as expected again

**Comment by phil-davis** [comment]
CI is sworking again. PR #17 passed after restarting it.

**Pull request closed without merging**
