### PR TITLE
Make enable/disable setting step clear that it is on the user management page

### PR DESCRIPTION
**Pull request by paurakhsharma**
# Description
Rephrase statement in usersSettingsPage

Related Issue #79

### CODE REVIEW

**Comment by phil-davis** [comment]
Do similar also for:
```
the administrator should be able to see last login of the users as
```

**Comment by paurakhsharma** [comment]
> Do similar also for:
> 
> ```
> the administrator should be able to see last login of the users as
> ```

Do you think this is necessary? Because, administrator only sees those infromation in user_management page.

**Comment by phil-davis** [comment]
@paurakhsharma backport this code to core stable10

**Comment by paurakhsharma** [comment]
Backport on: https://github.com/owncloud/core/pull/32922

**Pull request merged**
