### PR TITLE
Replace add-password with set_password

### PR DESCRIPTION
**Pull request by sharidas**
Replace add-password index with set_password.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
Fixes https://github.com/owncloud/core/issues/32621

**Comment by patrickjahns** [comment]
Should be sent to stable10 on core as well right?

**Comment by PVince81** [comment]
@sharidas please port to stable10 for 10.0.10

**Comment by sharidas** [comment]
Backport to stable10 https://github.com/owncloud/core/pull/32636

**Pull request merged**
