### PR TITLE
Do not delete token if token mismatch happens

### PR DESCRIPTION
**Pull request by sharidas**
Do not delete token if token mismatch happens.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
Fixes https://github.com/owncloud/core/issues/32651

**Comment by individual-it** [comment]
seems to fix the issue
Note: in case the user sets the password the token will be deleted in `OC\User\User::setPassword()` https://github.com/owncloud/core/blob/master/lib/private/User/User.php#L292

**Comment by sharidas** [comment]
Updated with unit test.

**Comment by PVince81** [comment]
@sharidas if you feel confident about CI results, you can backport now

**Comment by individual-it** [comment]
proposing to merge this after https://github.com/owncloud/user_management/pull/65 and to delete the `  @skip @issue-core-32651` tags in this PR

**Comment by sharidas** [comment]
Backport PR : https://github.com/owncloud/core/pull/32672

**Pull request merged**
