### PR TITLE
Add make tasks for l10n sync

### PR DESCRIPTION
**Pull request by tboerger**
Currently there are no unified make tasks to handle the localization
sync. This is my effort to integrate it to keep the CI jobs simple to
handle that.

Signed-off-by: Thomas Boerger <thomas@webhippie.de>

### CODE REVIEW

**Comment by tboerger** [comment]
Failing build is absolutely not related to this PR :(

**Comment by nonasoumy** [comment]
Lovely past

**Comment by nonasoumy** [comment]
Thank you for your help

**Comment by nonasoumy** [comment]
getting betther and better this time ! thank you community

**Comment by tboerger** [comment]
Ping @deepdiver1975 @pvince81

**Comment by DeepDiver1975** [comment]
Fine by me - seems reasonable.

**Comment by PVince81** [comment]
needs to be aligned with latest changes from @DeepDiver1975 to the reference Makefile

**Comment by PVince81** [comment]
aligned now

**Comment by PVince81** [comment]
ohhh, the conflicts

**Comment by PVince81** [comment]
conflicts resolved, should be ready for merge then

**Comment by tboerger** [comment]
Since Drone 1.0.0 we got cronjob support, so every plugin can handle the translation sync on their own now.

**Comment by paulijar** [comment]
@tboerger So what should the plugin do to handle the translation sync? Is there any documentation?

**Comment by tboerger** [comment]
We haven't migrated the plugin translation sync yet. A requirement would be running on drone ci.

**Pull request closed without merging**
