### PR TITLE
Acceptance test for adding groups using emojis in group names

### PR DESCRIPTION
**Pull request by bhawanaprasain**
## Description
We can create groups using emojis in group names .

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

### CODE REVIEW

**Comment by bhawanaprasain** [comment]
@phil-davis @individual-it Chrome driver supports test for emojis that have unicode of only 4 characters as Unicode. Refrence : [https://github.com/SeleniumHQ/selenium/issues/3257](url)

**Comment by bhawanaprasain** [comment]
@dpakach @skshetry @paurakhsharma please review on my PR.

**Comment by individual-it** [comment]
@bhawanaprasain please rebase and also backport to stable10 branch of core

**Comment by phil-davis** [comment]
@bhawanaprasain please rebase again. I guess something got merged in this repo just now.

**Comment by bhawanaprasain** [comment]
@phil-davis I have rebased again .

**Pull request merged**
