### PR TITLE
Fix response when user is removed from group

### PR DESCRIPTION
**Pull request by sharidas**
When user is successfully removed from the group
fix message that is sent by server.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
## Description
When users are added/removed to the group the group counts should automatically updated. No error message should be seen in the console when users are added successfully to the group or deleted from the group. This PR focuses on the deletion part, though.

## Issue
- Fixes https://github.com/owncloud/core/issues/35289

## Test done
- Create 2 groups `group1` and `group2`.
- Create users `user1`, `user2`, `user3`,`user4` ,`user5` ,`user6`.
- Add `user1`, `user2`, `user3` to `group1` and `user4`, `user5`,`user6` to `group2`.
- Now the numbers associated with `group1` and `group2`  are 3 each.
- Add `user6` to `group1`. Now user should see `group1` count is incremented to 4.
- The web console does not show any error.

Here is the screenshot:
everyone

**Comment by sharidas** [comment]
Backport to release-10.2.1: https://github.com/owncloud/core/pull/35570

**Comment by sharidas** [comment]
Kindly merge this PR please, the backports are merged.

**Comment by phil-davis** [comment]
@micbar @DeepDiver1975 merge requested ^

**Pull request merged**
