### PR TITLE
Fix the token exception classes to avoid infinite loop with getPrevious

### PR DESCRIPTION
**Pull request by sharidas**
Fix the users token exception class to avoid infinite
loop when getPrevious method is called.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
Fixes https://github.com/owncloud/core/issues/32684

**Comment by sharidas** [comment]
Restarting is not helping its failing again at https://drone.owncloud.com/owncloud/user_management/250/47

**Comment by PVince81** [comment]
hmm, the random "invalid quota value"

**Comment by phil-davis** [comment]
Same quota acceptance tests fail again.
I triggered CI without this change here #72 - let's see if that passes...

**Comment by phil-davis** [comment]
#72 got the same quota fails, so it is not the fault of this PR.
Issue #73 raised to look into it.

**Pull request merged**
